export interface Asset {
    id?: string,
    branchNum: number,
    branchName: string,
    rentContractId: number,
    managementContractId: number,
    bankName: string,
    address: string,
    town: string,
    isInRent: boolean | string,
    ownerName: string,
    areaSize: number,
    employeesCount: number,
    areaSizePerEmployee: number,
    monthleyNominalServiceFee: number,
    baseIndex: number,
    monthleyIndexedServiceFee: number,
    totalExpenses: number,
    rentBeginsAt: number | string,
    rentEndsAt: number | string,
    closeExitAt: number | string,
    priorNoticeMonthsCount: number,
    priorNoticeAt: number | string,
    optionEndsAt: number | string,
    moreExitPointsAndServiceFeeChange: string,
    contractStatus: string,
    contractRenewalAt: number | string,
    approverName: string,
    type: string
}